### ISSUE TITLE
swift 4 

### ISSUE THREAD

**Issue by AbdulazizAlmohsen** [krishnads/CustomeLocationPicker#1]
Possible to make it in swift 4 ? I will appreciat eit cuz I really need it

**Comment by krishnads** [comment]
You can convert it easily in swift 4. I can do it but I am really very busy in other stuffs. Sorry for that. Try out yourself. if you face any issue then let me know.

**Comment by AbdulazizAlmohsen** [comment]
I tried but I couldnt really. Hopefully in your free time you can do it sometime in the future.. cant wait
